import type { Metadata } from "next";
import "./globals.css";
import NavigationButtons from "./components/buttons/navigation_buttons/navigaiton_buttons";
import SocialMediaButtons from "./components/buttons/social_media_buttons/social_media_buttons";
import SmootScrolling from "./components/SmoothScrolling";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavigationButtons />
        <SocialMediaButtons />
        <SmootScrolling>{children}</SmootScrolling>
      </body>
    </html>
  );
}
